### ISSUE TITLE
Is the repo still mantained?

### ISSUE THREAD

**Issue by fedemengo** [tommyleo2/DockerClientpp#25]
I was wondering if the repo is still active

**Comment by tommyleo2** [comment]
Nope.  As long as the docker API is unchanged (hopefully so), it's still working.
Feel free to fork and make any modification.

BTW, esaurez is still mantaining his own fork. Check it out. https://github.com/esaurez/DockerClientpp

**Comment by tommyleo2** [comment]
> I was wondering if the repo is still active

Nope.  As long as the docker API is unchanged (hopefully so), it's still working.
Feel free to fork and make any modification.

BTW, esaurez is still mantaining his own fork. Check it out. https://github.com/esaurez/DockerClientpp

**Comment by fedemengo** [comment]
Alright, thanks!! Great job! :+1:
